[package]
name = "kotori"
version = "0.1.0"
publish = false

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[lints]
workspace = true

[build-dependencies.tauri-build]
version = "2.0.0-beta.11"
features = []

[dependencies]
ahash = "0.8.11"
anyhow = "1.0.82"
axum = "0.7.5"
futures = "0.3.30"
globset = "0.4.14"
image = "0.25.1"
indexmap = "2.2.6"
indoc = "2.0.5"
itertools = "0.12.1"
natord = "1.0.9"
rayon = "1.10.0"
serde_json = "1.0.115"
tauri-plugin-dialog = "2.0.0-beta.4"
tauri-plugin-manatsu = "0.9.7"
tauri-plugin-persisted-scope = "2.0.0-beta.4"
tauri-plugin-shell = "2.0.0-beta.3"
tauri-plugin-window-state = "2.0.0-beta.4"
tempfile = "3.10.1"
thiserror = "1.0.58"
tracing = "0.1"
walkdir = "2.5.0"
zip = "0.6.6"

[dependencies.migration]
version = "*"
path = "../migration"

[dependencies.sea-orm]
version = "0.12.15"
features = ["macros", "runtime-tokio-rustls", "sqlx-sqlite"]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.strum]
version = "0.26.2"
features = ["derive"]

[dependencies.tauri]
version = "2.0.0-beta.14"
features = ["protocol-asset"]

[dependencies.tauri-plugin-http]
version = "2.0.0-beta.4"
features = ["rustls-tls"]

[dependencies.tokio]
version = "1.37.0"
features = ["full"]

[dependencies.tracing-appender]
version = "0.2"
features = ["parking_lot"]

[dependencies.tracing-subscriber]
version = "0.3"
features = ["chrono", "env-filter", "fmt", "parking_lot", "registry"]

[features]
custom-protocol = ["tauri/custom-protocol"]
