[package]
name = "kotori"
version = "0.1.0"
edition = "2021"
rust-version = "1.76"
publish = false

[build-dependencies.tauri-build]
version = "1.5.1"
features = []

[dependencies]
anyhow = "1.0.81"
serde_json = "1.0.114"
tauri-plugin-manatsu = "*"
tauri-plugin-persisted-scope = "0.1.3"
tauri-plugin-window-state = "0.1.1"
thiserror = "1.0.58"
zip = "0.6.6"
migration = { path = "../migration" }

[dependencies.tauri]
version = "1.6.1"
features = ["dialog"]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.sea-orm]
version = "0.12.15"
features = ["macros", "runtime-tokio-rustls", "sqlx-sqlite"]

[dependencies.tokio]
version = "1.36.0"
features = ["macros", "rt-multi-thread"]

[features]
custom-protocol = ["tauri/custom-protocol"]
