[package]
name = "kotori"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"
publish = false

[build-dependencies.tauri-build]
version = "2.0.0-beta.10"
features = []

[dependencies]
anyhow = "1.0.81"
axum = "0.7.5"
chrono = "0.4.37"
futures = "0.3.30"
globset = "0.4.14"
indoc = "2.0.5"
itertools = "0.12.1"
natord = "1.0.9"
serde_json = "1.0.115"
tauri-plugin-dialog = "2.0.0-beta.3"
tauri-plugin-manatsu = "0.7.1"
tauri-plugin-persisted-scope = "2.0.0-beta.3"
tauri-plugin-window-state = "2.0.0-beta.3"
thiserror = "1.0.58"
tempfile = "3.10.1" # use for covers?
walkdir = "2.5.0"
zip = "0.6.6"

[dependencies.migration]
version = "*"
path = "../migration"

[dependencies.sea-orm]
version = "0.12.15"
features = ["macros", "runtime-tokio-rustls", "sqlx-sqlite"]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.strum]
version = "0.26.2"
features = ["derive"]

[dependencies.tauri]
version = "2.0.0-beta.13"
features = ["protocol-asset"]

[dependencies.tokio]
version = "1.37.0"
features = ["fs", "macros", "net", "process"]

[features]
custom-protocol = ["tauri/custom-protocol"]
