[package]
name = "kotori"
version = "0.1.0"

[package.description]
workspace = true

[package.authors]
workspace = true

[package.license]
workspace = true

[package.repository]
workspace = true

[package.edition]
workspace = true

[build-dependencies.tauri-build]
version = "1.5.1"
features = []

[dependencies]
serde_json = "1.0.114"
tauri-plugin-manatsu = "*"
tauri-plugin-persisted-scope = "0.1.3"
tauri-plugin-window-state = "0.1.1"
thiserror = "1.0.58"
zip = "0.6.6"

[dependencies.tauri]
version = "1.6.1"
features = [
    "path-all",
    "dialog-open",
]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[features]
custom-protocol = ["tauri/custom-protocol"]
