[package]
name = "kotori"
version = "0.1.0"

[package.authors]
workspace = true

[package.license]
workspace = true

[package.repository]
workspace = true

[package.edition]
workspace = true

[package.rust-version]
workspace = true

[package.publish]
workspace = true

[build-dependencies.tauri-build]
version = "1.5.1"
features = []

[dependencies]
anyhow = "1.0.81"
serde_json = "1.0.114"
tauri-plugin-manatsu = "*"
tauri-plugin-persisted-scope = "0.1.3"
tauri-plugin-window-state = "0.1.1"
thiserror = "1.0.58"
zip = "0.6.6"

[dependencies.tauri]
version = "1.6.1"
features = []

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.tokio]
version = "1.36.0"
features = ["macros", "rt-multi-thread"]

[features]
custom-protocol = ["tauri/custom-protocol"]
