[package]
name = "kotori"
version = "0.1.0"
description.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[build-dependencies.tauri-build]
version = "1.5"
features = []

[dependencies]
serde_json = "1.0"
tauri-plugin-manatsu = "0.1"

[dependencies.tauri]
version = "1.5"
features = []

[dependencies.serde]
version = "1.0"
features = ["derive"]

[features]
custom-protocol = ["tauri/custom-protocol"]
