[package]
name = "kotori"
version = "0.1.0"
edition = "2021"
rust-version = "1.76"
publish = false

[build-dependencies.tauri-build]
version = "2.0.0-beta.10"
features = []

[dependencies]
anyhow = "1.0.81"
chrono = "0.4.35"
serde_json = "1.0.114"
tauri-plugin-persisted-scope = "2.0.0-beta.3"
tauri-plugin-window-state = "2.0.0-beta.3"
tauri-plugin-dialog = "2.0.0-beta.3"
thiserror = "1.0.58"
zip = "0.6.6"
tempfile = "3.10.1"
globset = "0.4.14"
walkdir = "2.5.0"
natord = "1.0.9"

[dependencies.strum]
version = "0.26.2"
features = ["derive"]

[dependencies.migration]
version = "*"
path = "../migration"

[dependencies.tauri]
version = "2.0.0-beta.13"
features = ["protocol-asset"]

[dependencies.serde]
version = "1.0.197"
features = ["derive"]

[dependencies.sea-orm]
version = "0.12.15"
features = [
    "macros",
    "runtime-tokio-rustls",
    "sqlx-sqlite",
]

[dependencies.tokio]
version = "1.36.0"
features = [
    "fs",
    "macros",
    "rt-multi-thread",
]

[features]
custom-protocol = ["tauri/custom-protocol"]
