[package]
name = "migration"
version = "0.1.0"
edition = "2021"
rust-version = "1.77"
publish = false

[dependencies.async-std]
version = "1.12.0"
features = ["attributes", "tokio1"]

[dependencies.sea-orm-migration]
version = "0.12.15"
features = ["runtime-tokio-rustls", "sqlx-sqlite"]
