# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "desktop/src-tauri/src/database/schema.rs"
custom_type_derives = [
  "diesel::query_builder::QueryId",
  "Clone",
  "std::fmt::Debug",
]

[migrations_directory]
dir = "migrations"
