/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PButton: typeof import('primevue/button')['default']
    PDialog: typeof import('primevue/dialog')['default']
    PImage: typeof import('primevue/image')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMenubar: typeof import('primevue/menubar')['default']
    PProgressSpinner: typeof import('primevue/progressspinner')['default']
    PRating: typeof import('primevue/rating')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
