/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    PCard: typeof import('primevue/card')['default']
    PImage: typeof import('primevue/image')['default']
    PInputText: typeof import('primevue/inputtext')['default']
    PMenubar: typeof import('primevue/menubar')['default']
    PProgressSpinner: typeof import('primevue/progressspinner')['default']
    PSkeleton: typeof import('primevue/skeleton')['default']
    PVirtualScroller: typeof import('primevue/virtualscroller')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
